### PR TITLE
Fixes grouping albums by album artist rather than just album in the Music app

### PR DESCRIPTION
**Pull request by bhdouglass**

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Is there an issue filed? Where would I test this?

**Comment by bhdouglass** [comment]
Here is the MR for the music app: https://gitlab.com/ubports/apps/music-app/merge_requests/46
And here is the original issue: https://gitlab.com/ubports/apps/music-app/issues/44

If you build this with crossbuilder and compile the music app from that branch you should be able to test the changes (just make sure that you have a multi-artist album on your phone).

**Comment by bhdouglass** [comment]
Removed my build fixes and updated to include the changes from `xenial_-_mediascanner-build`. :crossed_fingers: hopefully it builds now!

**Comment by Flohack74** [comment]
Unfortunately it does not ;)

**Comment by bhdouglass** [comment]
Dangit!

**Comment by bhdouglass** [comment]
5th time, maybe?

**Comment by bhdouglass** [comment]
yay!

**Comment by bhdouglass** [comment]
@UniversalSuperBox is this good to go?

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
This tests fine to me, however the commits from #2 have been pulled in uncleanly. Please rebase your branch or reopen this PR to have a clean commit log again.

**Comment by bhdouglass** [comment]
Ok, should be good now, provided tests pass again.

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
This makes backwards-incompatible API changes. If we must do this, we'll need to also determine which apps link against this and create a framework version that is not backwards compatible.

**Comment by bhdouglass** [comment]
@UniversalSuperBox  I updated the Album class to not have breaking changes. But the dbus stuff was less straight forward. But since the dbus should just be used by the included qml lib I think everything should be fine.

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
